<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.6.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="concept\ConceptControl.cs" />
    <Compile Update="liquidation\LiquidationForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="supplier\SupplierControl.cs" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="concept\ConceptForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="supplier\SupplierForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="consortium\ConsortiumForm.cs">
      <SubType>Form</SubType>
    </Compile>
  </ItemGroup>

</Project>
